version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    # Не решение для продакшен, лучше использовать .env файл 
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user_for_migrate
      - DB_PASSWORD=test
      - DB_NAME=rates_db  
    volumes:
      - ./db/migrations:/Rates/db/migrations

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: rates_db
      MYSQL_USER: user_for_migrate
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
